name: simclr-cifar10-experiment
dataset: 
  name: cifar10
  image_size: 32
  num_workers: 4

model: 
  name: simclr_mi
  backbone: resnet18_cifar_variant1

load_model: False

train:
  optimizer: 
    name: lars_simclr
    weight_decay: 1.e-6
    momentum: 0.9
  warmup_epochs: 10
  warmup_lr: 0
  base_lr: 0.3
  final_lr: 0
  num_epochs: 800 # this parameter influence the lr decay
  stop_at_epoch: 800 # has to be smaller than num_epochs
  batch_size: 512
  knn_monitor: True # knn monitor will take more time
  knn_interval: 1
  knn_k: 200

eval: # linear evaluation, False will turn off automatic evaluation after training
  optimizer: 
    name: sgd
    weight_decay: 0
    momentum: 0.9
  warmup_lr: 0
  warmup_epochs: 0
  base_lr: 30
  final_lr: 0
  disc_lr: 0.001
  batch_size: 256
  num_epochs: 30

logger:
  tensorboard: True
  matplotlib: False
  
seed: null # None type for yaml file
# two things might lead to stochastic behavior other than seed:
# worker_init_fn from dataloader and torch.nn.functional.interpolate 
# (keep this in mind if you want to achieve 100% deterministic)




